filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    stream: all
    symlinks: true
    processors:
      - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["${ELASTIC_HOST}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.verification_mode: "none"

setup.kibana:
  hosts: ["${ELASTIC_HOST}"]
  username: "${ELASTIC_USERNAME}"
  password: "${ELASTIC_PASSWORD}"
  ssl.verification_mode: "none"
