name: ESLint Code Quality

on:
  push:
  pull_request:

jobs:
  eslint_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (in Client folder)
        working-directory: ./Client
        run: npm ci

      - name: Run ESLint
        working-directory: ./Client
        run: npm run lint
