name: Build RabbitMQ Package

permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - main
    paths:
      - "RabbitMQ/**"
      - "setup.py"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install build

      - name: Clean old builds
        run: rm -rf dist

      - name: Build RabbitMQ package
        working-directory: RabbitMQ
        run: python -m build

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: rabbitmq-package
          path: RabbitMQ/dist/*

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete old artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-last: 2
